include:
- hello.go
kind: ArchiveUploadSpec
name: hello-go

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-go-9s6r
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://hello-go
status:
  buildstatus: pending

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-go
  namespace: default
spec:
  environment:
    name: go
    namespace: default
  package:
    functionName: Handler
    packageref:
      name: hello-go-9s6r
      namespace: default
